### PR TITLE
Move Retweet item above Reply in pulldown

### PR DESCRIPTION
**Pull request by CODeRUS**

### CODE REVIEW

**Comment by veskuh** [comment]
Not sure about this, I retweet more often then I reply so I kinda like the way it is.. But that's just me.. Would be nice to get couple of comments what people prefer..

**Comment by siteshwar** [comment]
@CODeRUS Why do you want to change ordering of retweet and reply items ?

**Comment by CODeRUS** [comment]
@veskuh good point, tweeted link :)
@siteshwar because i'm using reply often than retweet. When retweeting i never open tweet page and using combobox menu

**Comment by kimmoli** [comment]
I prefer them as they are now (as i know what is where) 
But there is some discrepancy, even order is the same:
Combo opens downwards from the tweet, reply is first choice, 
in tweetpage pulldown it opens from up, retweet is first choice.

**Comment by Morpog** [comment]
It depends on the day :)
I'm fine with both orderings, but as kimmoli already said it should be same ordering in combobox and pulley.

**Comment by siteshwar** [comment]
My vote goes to consistency too ;)

**Comment by veskuh** [comment]
Ok, so I guess constancy is good and thus this will make things better.

**Comment by Vistaus** [comment]
I'm all in with veskuh's original comment: I retweet a lot so I'm used to Tweetian having RT below Reply. Which is how I like it.

**Comment by Vistaus** [comment]
Can't you at least make it a setting? So that people can choose whether they want RT or Reply below? I'm not updating to the next version if it's not at least an option to choose the old behaviour.

**Comment by veskuh** [comment]
No. We are not making settings for every little detail.

**Comment by Vistaus** [comment]
But that's unfair. At least 3 people here said they liked the old behaviour while only two said they wanted a change and one didn't care. So it's not like there was a majority in favor of this. It was a tie at best. So the fair thing to do would be to at least make the old behaviour an option or re-run the 'vote' (as far as you can call it a vote).

**Comment by CODeRUS** [comment]
Can you explain why it so much important for you? Why you cant use context menu or drag one item more? Or fast drag and click on item you want? Why?

**Comment by Vistaus** [comment]
I don't ever use the context menu and fast drag and click is slow and most of all defeats the whole purpose of the pulley menu. I'm using the pulley menu because it's easy and fast to use, esp. when you know where the menu options are. In this case RT is below Reply, which makes it a very fast way to RT a tweet. I use Tweetian for it's fast navigation (which includes RT'ing), otherwise I might as well use Jolla's feed or the mobile twitter website. The first option is the easiest to hit with a pulley menu, so it's nice to have the first option be the most used one. I use RT more than Reply, and a few other people in the comments here said the same.

**Comment by CODeRUS** [comment]
"I don't ever use the context menu" < thats enough for me to make a decision :)

**Pull request merged**
