### PR TITLE
Added option to adjust font size

### PR DESCRIPTION
**Pull request by CODeRUS**

### CODE REVIEW

**Comment by veskuh** [comment]
Tweet delegates do not properly resize themselves after size change. After restart all is fine. The issue is not in this pull request though. There seems to be some issues in Qt's Text.RichText handling bits. I already did nasty hack for handling width change. Perhaps same hack  https://github.com/veskuh/Tweetian/commit/357ce89de6d267d6647cd7376191047233bb49f4 would  force delegates properly relayout themselves after font size change

**Comment by veskuh** [comment]
The other option I'm considering is to just show the plain text version in tweet lists. The upside of that is that it makes performance even better.

**Comment by CODeRUS** [comment]
what is rich text for? linkify urls and emails?

**Comment by veskuh** [comment]
Yes, for formatting links. For normal links styled text and underline would be ok, but it does not look good on hashtag and email links and you cannot get rid of it in Text.StyledText.

**Comment by CODeRUS** [comment]
i didnt understand. what wrong with StyledText?

**Comment by veskuh** [comment]
With styled text you cannot remove the underline from links.

**Comment by veskuh** [comment]
Ok, I'm merging this now. In any case user can restart to get the first delegates to relayout properly. Thanks.

**Pull request merged**
